#include<vector>
#include "gtest/gtest.h"
#include "leetcode.h"
#include "acwing.h"
#include "lintcode.h"

using namespace std;

namespace leetcode {
    namespace excel_sheet_column_title {
        TEST(excel_sheet_column_title, case1) {
            ASSERT_EQ(std::string("A"), Solution::convertToTitle(1));
        }

        TEST(excel_sheet_column_title, case2) {
            ASSERT_EQ(std::string("AB"), Solution::convertToTitle(28));
        }

        TEST(excel_sheet_column_title, case3) {
            ASSERT_EQ(std::string("ZY"), Solution::convertToTitle(701));
        }

        TEST(excel_sheet_column_title, case4) {
            ASSERT_EQ(std::string("FXSHRXW"), Solution::convertToTitle(2147483647));
        }

        TEST(excel_sheet_column_title, case5) {
            ASSERT_EQ(std::string("AZ"), Solution::convertToTitle(52));
        }
    }

    namespace majority_element {
        TEST(majority_element, case1) {
            Solution sol = Solution();
            int arr[] = {3, 2, 3};
            auto vec = std::vector<int>(arr, arr + 3);
            ASSERT_EQ(3, sol.majorityElement(vec));
        }

        TEST(majority_element, case2) {
            Solution sol = Solution();
            int arr[] = {2, 2, 1, 1, 1, 2, 2};
            auto vec = std::vector<int>(arr, arr + 7);
            ASSERT_EQ(2, sol.majorityElement(vec));
        }

        TEST(majority_element, case3) {
            Solution sol = Solution();
            int arr[] = {3, 2, 3};
            auto vec = std::vector<int>(arr, arr + 3);
            ASSERT_EQ(3, sol.majorityElement(vec));
        }
    }

    namespace excel_sheet_column_number {
        TEST(excel_sheet_column_number, case1) {
            ASSERT_EQ(1, Solution::titleToNumber("A"));
        }

        TEST(excel_sheet_column_number, case2) {
            ASSERT_EQ(28, Solution::titleToNumber("AB"));
        }

        TEST(excel_sheet_column_number, case3) {
            ASSERT_EQ(701, Solution::titleToNumber("ZY"));
        }

        TEST(excel_sheet_column_number, case4) {
            ASSERT_EQ(2147483647, Solution::titleToNumber("FXSHRXW"));
        }
    }

    namespace concatenated_words {
        TEST(concatenated_words, case1) {
            vector<basic_string<char>> input = vector<basic_string<char>>();
            input.emplace_back("cat");
            input.emplace_back("cats");
            input.emplace_back("catsdogcats");
            input.emplace_back("dog");
            input.emplace_back("dogcatsdog");
            input.emplace_back("hippopotamuses");
            input.emplace_back("rat");
            input.emplace_back("ratcatdogcat");
            auto ans = Solution::findAllConcatenatedWordsInADict(input);
            vector<string> output = vector<string>();
            output.emplace_back("catsdogcats");
            output.emplace_back("dogcatsdog");
            output.emplace_back("ratcatdogcat");
            for (const string &str: ans) {
                ASSERT_TRUE(find(output.cbegin(), output.cend(), str) != output.cend());
            }
            for (const string &str: output) {
                ASSERT_TRUE(find(ans.cbegin(), ans.cend(), str) != ans.cend());
            }
            ASSERT_EQ(ans.size(), output.size());
        }

        TEST(concatenated_words, case2) {
            vector<basic_string<char>> input = vector<basic_string<char>>();
            input.emplace_back("cat");
            input.emplace_back("dog");
            input.emplace_back("catdog");
            auto ans = Solution::findAllConcatenatedWordsInADict(input);
            vector<string> output = vector<string>();
            output.emplace_back("catdog");
            for (const string &str: ans) {
                ASSERT_TRUE(find(output.cbegin(), output.cend(), str) != output.cend());
            }
            for (const string &str: output) {
                ASSERT_TRUE(find(ans.cbegin(), ans.cend(), str) != ans.cend());
            }
            ASSERT_EQ(ans.size(), output.size());
        }

        TEST(concatenated_words, case3) {
            vector<basic_string<char>> input = vector<basic_string<char>>();
            input.emplace_back("rfkqyuqfjkx");
            input.emplace_back("");
            input.emplace_back("vnrtysfrzrmzl");
            input.emplace_back("gfve");
            input.emplace_back("qfpd");
            input.emplace_back("lqdqrrcrwdnxeuo");
            input.emplace_back("q");
            input.emplace_back("klaitgdphcspij");
            input.emplace_back("hbsfyfv");
            input.emplace_back("adzpbfudkklrw");
            input.emplace_back("aozmixr");
            input.emplace_back("ife");
            input.emplace_back("feclhbvfuk");
            input.emplace_back("yeqfqojwtw");
            input.emplace_back("sileeztxwjl");
            input.emplace_back("ngbqqmbxqcqp");
            input.emplace_back("khhqr");
            input.emplace_back("dwfcayssyoqc");
            input.emplace_back("omwufbdfxu");
            input.emplace_back("zhift");
            input.emplace_back("kczvhsybloet");
            input.emplace_back("crfhpxprbsshsjxd");
            input.emplace_back("ilebxwbcto");
            input.emplace_back("yaxzfbjbkrxi");
            input.emplace_back("imqpzwmshlpj");
            input.emplace_back("ta");
            input.emplace_back("hbuxhwadlpto");
            input.emplace_back("eziwkmg");
            input.emplace_back("ovqzgdixrpddzp");
            input.emplace_back("c");
            input.emplace_back("wnqwqecyjyib");
            input.emplace_back("jy");
            input.emplace_back("mjfqwltvzk");
            input.emplace_back("tpvo");
            input.emplace_back("phckcyufdqml");
            input.emplace_back("lim");
            input.emplace_back("lfz");
            input.emplace_back("tgygdt");
            input.emplace_back("nhcvpf");
            input.emplace_back("fbrpzlk");
            input.emplace_back("shwywshtdgmb");
            input.emplace_back("bkkxcvg");
            input.emplace_back("monmwvytby");
            input.emplace_back("nuqhmfj");
            input.emplace_back("qtg");
            input.emplace_back("cwkuzyamnerp");
            input.emplace_back("fmwevhwlezo");
            input.emplace_back("ye");
            input.emplace_back("hbrcewjxvcezi");
            input.emplace_back("tiq");
            input.emplace_back("tfsrptug");
            input.emplace_back("iznorvonzjfea");
            input.emplace_back("gama");
            input.emplace_back("apwlmbzit");
            input.emplace_back("s");
            input.emplace_back("hzkosvn");
            input.emplace_back("nberblt");
            input.emplace_back("kggdgpljfisylt");
            input.emplace_back("mf");
            input.emplace_back("h");
            input.emplace_back("bljvkypcflsaqe");
            input.emplace_back("cijcyrgmqirz");
            input.emplace_back("iaxakholawoydvch");
            input.emplace_back("e");
            input.emplace_back("gttxwpuk");
            input.emplace_back("jf");
            input.emplace_back("xbrtspfttota");
            input.emplace_back("sngqvoijxuv");
            input.emplace_back("bztvaal");
            input.emplace_back("zxbshnrvbykjql");
            input.emplace_back("zz");
            input.emplace_back("mlvyoshiktodnsjj");
            input.emplace_back("qplci");
            input.emplace_back("lzqrxl");
            input.emplace_back("qxru");
            input.emplace_back("ygjtyzleizme");
            input.emplace_back("inx");
            input.emplace_back("lwhhjwsl");
            input.emplace_back("endjvxjyghrveu");
            input.emplace_back("phknqtsdtwxcktmw");
            input.emplace_back("wsdthzmlmbhjkm");
            input.emplace_back("u");
            input.emplace_back("pbqurqfxgqlojmws");
            input.emplace_back("mowsjvpvhznbsi");
            input.emplace_back("hdkbdxqg");
            input.emplace_back("ge");
            input.emplace_back("pzchrgef");
            input.emplace_back("ukmcowoe");
            input.emplace_back("nwhpiid");
            input.emplace_back("xdnnl");
            input.emplace_back("n");
            input.emplace_back("yjyssbsoc");
            input.emplace_back("cdzcuunkrf");
            input.emplace_back("uvouaghhcyvmlk");
            input.emplace_back("aajpfpyljt");
            input.emplace_back("jpyntsefxi");
            input.emplace_back("wjute");
            input.emplace_back("y");
            input.emplace_back("pbcnmhf");
            input.emplace_back("qmmidmvkn");
            input.emplace_back("xmywegmtuno");
            input.emplace_back("vuzygv");
            input.emplace_back("uxtrdsdfzfssmel");
            input.emplace_back("odjgdgzfmrazvnd");
            input.emplace_back("a");
            input.emplace_back("rdkugsbdpawxi");
            input.emplace_back("ivd");
            input.emplace_back("bbqeonycaegxfj");
            input.emplace_back("lrfkraoheucsvpi");
            input.emplace_back("eqrswgkaaaohxx");
            input.emplace_back("hqjtkqaqh");
            input.emplace_back("berbpmglbjipnuj");
            input.emplace_back("wogwczlkyrde");
            input.emplace_back("aqufowbig");
            input.emplace_back("snjniegvdvotu");
            input.emplace_back("ocedkt");
            input.emplace_back("bbufnxorixibbd");
            input.emplace_back("rzuqsyr");
            input.emplace_back("qghoy");
            input.emplace_back("evcuanuujszitaoa");
            input.emplace_back("wsx");
            input.emplace_back("glafbwzdd");
            input.emplace_back("znrvjqeyqi");
            input.emplace_back("npitruijvyllsi");
            input.emplace_back("objltu");
            input.emplace_back("ryp");
            input.emplace_back("nvybsfrxtlfmp");
            input.emplace_back("id");
            input.emplace_back("zoolzslgd");
            input.emplace_back("owijatklvjzscizr");
            input.emplace_back("upmsoxftumyxifyu");
            input.emplace_back("xucubv");
            input.emplace_back("fctkqlroq");
            input.emplace_back("zjv");
            input.emplace_back("wzi");
            input.emplace_back("ppvs");
            input.emplace_back("mflvioemycnphfjt");
            input.emplace_back("nwedtubynsb");
            input.emplace_back("repgcx");
            input.emplace_back("gsfomhvpmy");
            input.emplace_back("kdohe");
            input.emplace_back("tyycsibbeaxn");
            input.emplace_back("wjkfvabn");
            input.emplace_back("llkmagl");
            input.emplace_back("thkglauzgkeuly");
            input.emplace_back("paeurdvexqlw");
            input.emplace_back("akdt");
            input.emplace_back("ihmfrj");
            input.emplace_back("janxk");
            input.emplace_back("rqdll");
            input.emplace_back("cyhbsuxnlftmjc");
            input.emplace_back("yybwsjmajbwtuhkk");
            input.emplace_back("ovytgaufpjl");
            input.emplace_back("iwbnzhybsx");
            input.emplace_back("mumbh");
            input.emplace_back("jqmdabmyu");
            input.emplace_back("br");
            input.emplace_back("lwstjkoxbczkj");
            input.emplace_back("vhsgzvwiixxaob");
            input.emplace_back("fso");
            input.emplace_back("qnebmfl");
            input.emplace_back("ooetjiz");
            input.emplace_back("lq");
            input.emplace_back("msxphqdgz");
            input.emplace_back("mqhoggvrvjqrp");
            input.emplace_back("xbhkkfg");
            input.emplace_back("zxjegsyovdrmw");
            input.emplace_back("jav");
            input.emplace_back("mshoj");
            input.emplace_back("ax");
            input.emplace_back("biztkfomz");
            input.emplace_back("hujdmcyxdqteqja");
            input.emplace_back("gqgsomonv");
            input.emplace_back("reqqzzpw");
            input.emplace_back("lihdnvud");
            input.emplace_back("lznfhbaokxvce");
            input.emplace_back("fhxbldylqqewdnj");
            input.emplace_back("rlbskqgfvn");
            input.emplace_back("lfvobeyolyy");
            input.emplace_back("v");
            input.emplace_back("iwh");
            input.emplace_back("fpbuiujlolnjl");
            input.emplace_back("gvwxljbo");
            input.emplace_back("ypaotdzjxxrsc");
            input.emplace_back("mwrvel");
            input.emplace_back("umzpnoiei");
            input.emplace_back("ogwilaswn");
            input.emplace_back("yw");
            input.emplace_back("egdgye");
            input.emplace_back("hsrznlzrf");
            input.emplace_back("mwdgxaigmxpy");
            input.emplace_back("yaqgault");
            input.emplace_back("dtlg");
            input.emplace_back("cyvfiykmkllf");
            input.emplace_back("zxqyhvizqmamj");
            input.emplace_back("lvvgoifltzywueyp");
            input.emplace_back("abinmy");
            input.emplace_back("ppzaecvmx");
            input.emplace_back("qsmzc");
            input.emplace_back("iddymnl");
            input.emplace_back("uskihek");
            input.emplace_back("evxtehxtbthq");
            input.emplace_back("jvtfzddlgch");
            input.emplace_back("czohpyewf");
            input.emplace_back("ufzazyxtqxcu");
            input.emplace_back("brxpfymuvfvs");
            input.emplace_back("xrrcfuusicc");
            input.emplace_back("aqhlswbzievij");
            input.emplace_back("rv");
            input.emplace_back("udvmara");
            input.emplace_back("upityz");
            input.emplace_back("fecd");
            input.emplace_back("suxteeitxtg");
            input.emplace_back("dfuydrtbfypbn");
            input.emplace_back("cypqodxr");
            input.emplace_back("wikfuxwjht");
            input.emplace_back("jrliuaifpp");
            input.emplace_back("vkmxys");
            input.emplace_back("wvpfyfpkvgthq");
            input.emplace_back("rmajxis");
            input.emplace_back("jncxgviyu");
            input.emplace_back("av");
            input.emplace_back("nmhskodmidaj");
            input.emplace_back("lkfrimprrhen");
            input.emplace_back("uip");
            input.emplace_back("hstyopbvuiqc");
            input.emplace_back("p");
            input.emplace_back("vwduwmjpblqo");
            input.emplace_back("fnxwgqtvwztje");
            input.emplace_back("xwnbcuggl");
            input.emplace_back("iehimvoymyjasin");
            input.emplace_back("spsqiu");
            input.emplace_back("flhyfac");
            input.emplace_back("mqrbq");
            input.emplace_back("pstsxhplrrmbeddv");
            input.emplace_back("hnegtuxx");
            input.emplace_back("alsyxezjwtlwmxv");
            input.emplace_back("jtxytykkcku");
            input.emplace_back("bhhlovgcx");
            input.emplace_back("xhhivxnutkx");
            input.emplace_back("had");
            input.emplace_back("aysulvk");
            input.emplace_back("m");
            input.emplace_back("anhsyxli");
            input.emplace_back("jdkgfc");
            input.emplace_back("potn");
            input.emplace_back("lcibpxkidmwexp");
            input.emplace_back("gwoxjicdkv");
            input.emplace_back("tltienw");
            input.emplace_back("ngiutnuqbzi");
            input.emplace_back("o");
            input.emplace_back("tzlyb");
            input.emplace_back("vumnwehj");
            input.emplace_back("os");
            input.emplace_back("np");
            input.emplace_back("lhv");
            input.emplace_back("uzvgyeette");
            input.emplace_back("ipfvr");
            input.emplace_back("lpprjjalchhhcmh");
            input.emplace_back("k");
            input.emplace_back("pciulccqssaqgd");
            input.emplace_back("tp");
            input.emplace_back("dmzdzveslyjad");
            input.emplace_back("wtsbhgkd");
            input.emplace_back("eouxbldsxzm");
            input.emplace_back("vhtonlampljgzyve");
            input.emplace_back("xhnlcrldtfthul");
            input.emplace_back("xhflc");
            input.emplace_back("upgei");
            input.emplace_back("rlaks");
            input.emplace_back("yfqvnvtnqspyjbxr");
            input.emplace_back("phouoyhvls");
            input.emplace_back("voibuvbhhjcdflvl");
            input.emplace_back("rgorfbjrofokggaf");
            input.emplace_back("dqhqats");
            input.emplace_back("zchpicyuawpovm");
            input.emplace_back("yzwfor");
            input.emplace_back("koat");
            input.emplace_back("pybf");
            input.emplace_back("fhdzsbiyjld");
            input.emplace_back("gznfnqydisn");
            input.emplace_back("xz");
            input.emplace_back("po");
            input.emplace_back("tcjup");
            input.emplace_back("wygsnxk");
            input.emplace_back("kqlima");
            input.emplace_back("fgxnuohrnhg");
            input.emplace_back("publurhztntgmimc");
            input.emplace_back("zuufzphd");
            input.emplace_back("iucrmmmjqtcey");
            input.emplace_back("wnnbq");
            input.emplace_back("rghzyz");
            input.emplace_back("ukjqsjbmp");
            input.emplace_back("mdtrgv");
            input.emplace_back("vyeikgjdnml");
            input.emplace_back("kxwldnmi");
            input.emplace_back("apzuhsbssaxj");
            input.emplace_back("tkbkoljyodlipof");
            input.emplace_back("nkq");
            input.emplace_back("ktwtj");
            input.emplace_back("vgmkgjwle");
            input.emplace_back("t");
            input.emplace_back("agylw");
            input.emplace_back("vomtuy");
            input.emplace_back("jbtvitkqn");
            input.emplace_back("vtdxwrclpspcn");
            input.emplace_back("rdrls");
            input.emplace_back("yxfeoh");
            input.emplace_back("upj");
            input.emplace_back("myctacn");
            input.emplace_back("fdnor");
            input.emplace_back("ahqghzhoqprgkym");
            input.emplace_back("phiuvdv");
            input.emplace_back("jp");
            input.emplace_back("fdgpouzjwbq");
            input.emplace_back("hqoyefmugjvewhxu");
            input.emplace_back("qfzwuwe");
            input.emplace_back("fnsbijkeepyxry");
            input.emplace_back("oja");
            input.emplace_back("qthkcij");
            input.emplace_back("zpmqfbmnr");
            input.emplace_back("ybaibmzonzqlnmd");
            input.emplace_back("svo");
            input.emplace_back("gjftyfehik");
            input.emplace_back("jfrfgznuaytvaegm");
            input.emplace_back("aljhrx");
            input.emplace_back("odjq");
            input.emplace_back("ogwaxrssjxgvnka");
            input.emplace_back("zaqswwofedxj");
            input.emplace_back("lugpktauixp");
            input.emplace_back("dc");
            input.emplace_back("odknlbvxrs");
            input.emplace_back("jeobu");
            input.emplace_back("vqythyvzxbcgrlbg");
            input.emplace_back("hwc");
            input.emplace_back("erpbaxq");
            input.emplace_back("ujxcxck");
            input.emplace_back("rrklkb");
            input.emplace_back("wlrwyuy");
            input.emplace_back("zmg");
            input.emplace_back("yyhga");
            input.emplace_back("xwdbycdu");
            input.emplace_back("htedgvsrhchox");
            input.emplace_back("wr");
            input.emplace_back("suhesetv");
            input.emplace_back("jonqwhkwezjvjgg");
            input.emplace_back("sqqyrxtjkcalswq");
            input.emplace_back("hvyimhe");
            input.emplace_back("pjzdkmoue");
            input.emplace_back("zbphmgoxq");
            input.emplace_back("lbdlcumdgixjbcq");
            input.emplace_back("ztzdjqmadthtdmv");
            input.emplace_back("qcagsyqggcf");
            input.emplace_back("if");
            input.emplace_back("jpjxcjyi");
            input.emplace_back("chyicqibxdgkqtg");
            input.emplace_back("iwpdklhum");
            input.emplace_back("wljmg");
            input.emplace_back("micmun");
            input.emplace_back("npdbamofynykqv");
            input.emplace_back("ijsnfkpfy");
            input.emplace_back("lmq");
            input.emplace_back("oyjmeqvhcrvgm");
            input.emplace_back("mqopusqktdthpvz");
            input.emplace_back("fz");
            input.emplace_back("r");
            input.emplace_back("qbsqtipq");
            input.emplace_back("nxtsnason");
            input.emplace_back("xbpipyhh");
            input.emplace_back("topsuqomfjrd");
            input.emplace_back("islif");
            input.emplace_back("gbndakaq");
            input.emplace_back("bwnkxnwpzeoohlx");
            input.emplace_back("hrtbfnq");
            input.emplace_back("fguvomeepxoffg");
            input.emplace_back("mat");
            input.emplace_back("dzfpfnwbfuj");
            input.emplace_back("onlvy");
            input.emplace_back("cwcchvsasdylb");
            input.emplace_back("rxfcztzqopdi");
            input.emplace_back("ybrhodjn");
            input.emplace_back("oqkijy");
            input.emplace_back("ncvrjo");
            input.emplace_back("dphbfaal");
            input.emplace_back("xgtpdtkz");
            input.emplace_back("sebevsopjvciwljf");
            input.emplace_back("rcumyacqdapwczen");
            input.emplace_back("mabkapuoud");
            input.emplace_back("pbozezeygljfftvy");
            input.emplace_back("bvazmzbndl");
            input.emplace_back("vl");
            input.emplace_back("qiaixdtbhqvlzd");
            input.emplace_back("ffjfb");
            input.emplace_back("svthrfmkoxbho");
            input.emplace_back("cvet");
            input.emplace_back("ucgqyvopafyttrh");
            input.emplace_back("lbgihet");
            input.emplace_back("naiqyufxffdw");
            input.emplace_back("vruh");
            input.emplace_back("uz");
            input.emplace_back("ukffmudygjavem");
            input.emplace_back("dccamymhp");
            input.emplace_back("wofwgjkykm");
            input.emplace_back("fbuujzxhln");
            input.emplace_back("kmm");
            input.emplace_back("lzandlltowjpwsal");
            input.emplace_back("fapfvrmezbsjxs");
            input.emplace_back("wiw");
            input.emplace_back("sc");
            input.emplace_back("soqlh");
            input.emplace_back("hzaplclkwl");
            input.emplace_back("gcdqbcdwbwa");
            input.emplace_back("gadgt");
            input.emplace_back("pgowefka");
            input.emplace_back("juffuguqepwnfh");
            input.emplace_back("nbuinl");
            input.emplace_back("cpdxf");
            input.emplace_back("sox");
            input.emplace_back("fq");
            input.emplace_back("lfnrhgsxkhx");
            input.emplace_back("xrcorfygjxpi");
            input.emplace_back("mwtqjwbhgh");
            input.emplace_back("loc");
            input.emplace_back("fkglorkkvx");
            input.emplace_back("nlzdhucvayrz");
            input.emplace_back("azefobxutitrf");
            input.emplace_back("rlrstkcbtikklmh");
            input.emplace_back("ggk");
            input.emplace_back("sbphcejuylh");
            input.emplace_back("nraoenhd");
            input.emplace_back("zngyodiqlchxyycx");
            input.emplace_back("rrbhfwohfv");
            input.emplace_back("krzolrglgn");
            input.emplace_back("cpjesdzy");
            input.emplace_back("yoifoyg");
            input.emplace_back("hqqevqjugi");
            input.emplace_back("ahmv");
            input.emplace_back("xgaujnyclcjq");
            input.emplace_back("evhyfnlohavrj");
            input.emplace_back("byyvhgh");
            input.emplace_back("hyw");
            input.emplace_back("kedhvwy");
            input.emplace_back("ysljsqminajfipds");
            input.emplace_back("rglnpxfqwu");
            input.emplace_back("cibpynkxg");
            input.emplace_back("su");
            input.emplace_back("mbntqrlwyampdg");
            input.emplace_back("nig");
            input.emplace_back("ldhlhqdyjcfhu");
            input.emplace_back("jfymrbafmyoc");
            input.emplace_back("tyjmnhlfnrtz");
            input.emplace_back("dlazixtlxyvm");
            input.emplace_back("fbiguhsfuqo");
            input.emplace_back("rhymsno");
            input.emplace_back("rkbdlchs");
            input.emplace_back("ocbbwwd");
            input.emplace_back("astaiamnepwkya");
            input.emplace_back("mplirup");
            input.emplace_back("edkxjq");
            input.emplace_back("g");
            input.emplace_back("exlwulswtvot");
            input.emplace_back("tlnc");
            input.emplace_back("vnrrzerz");
            input.emplace_back("ygeraoozbtt");
            input.emplace_back("yyifkin");
            input.emplace_back("eo");
            input.emplace_back("ua");
            input.emplace_back("qgztvqdolf");
            input.emplace_back("rlzddjzcshvd");
            input.emplace_back("khxkdxflwxme");
            input.emplace_back("kk");
            input.emplace_back("zylbhoaac");
            input.emplace_back("cw");
            input.emplace_back("iizic");
            input.emplace_back("gcdxstpz");
            input.emplace_back("kjwdqeg");
            input.emplace_back("earjrncmmkdel");
            input.emplace_back("kbesuhquepj");
            input.emplace_back("nrzbllldgdmyrpgl");
            input.emplace_back("hllwnqozf");
            input.emplace_back("djpchowhwevbqvjj");
            input.emplace_back("zsmhylnjpktb");
            input.emplace_back("pxnktxkm");
            input.emplace_back("fxwiaqqb");
            input.emplace_back("qjwufmwresfsfaok");
            input.emplace_back("aa");
            input.emplace_back("d");
            input.emplace_back("iobioqm");
            input.emplace_back("svjgzk");
            input.emplace_back("khbzp");
            input.emplace_back("euexyudhrioi");
            input.emplace_back("yqsj");
            input.emplace_back("ngrwqpoh");
            input.emplace_back("rwuvd");
            input.emplace_back("eruffmlg");
            input.emplace_back("bxzovyew");
            input.emplace_back("faz");
            input.emplace_back("pmvfvyguqdi");
            input.emplace_back("jlxnoixsy");
            input.emplace_back("hyfrdngjf");
            input.emplace_back("ly");
            input.emplace_back("eibcapetpmeaid");
            input.emplace_back("tpnwwiif");
            input.emplace_back("pfgsp");
            input.emplace_back("kvhhwkzvtvlhhb");
            input.emplace_back("pjxurgqbtldims");
            input.emplace_back("rncplkeweoirje");
            input.emplace_back("akyprzzphew");
            input.emplace_back("wyvfpjyglzrmhfqp");
            input.emplace_back("ubheeqt");
            input.emplace_back("rmbxlcmn");
            input.emplace_back("taqakgim");
            input.emplace_back("apsbu");
            input.emplace_back("khwnykughmwrlk");
            input.emplace_back("vtdlzwpbhcsbvjno");
            input.emplace_back("tffmjggrmyil");
            input.emplace_back("schgwrrzt");
            input.emplace_back("mvndmua");
            input.emplace_back("nlwpw");
            input.emplace_back("glvbtkegzjs");
            input.emplace_back("piwllpgnlpcnezqs");
            input.emplace_back("xkelind");
            input.emplace_back("urtxsezrwz");
            input.emplace_back("zechoc");
            input.emplace_back("vfaimxrqnyiq");
            input.emplace_back("ybugjsblhzfravzn");
            input.emplace_back("btgcpqwovwp");
            input.emplace_back("zgxgodlhmix");
            input.emplace_back("sfzdknoxzassc");
            input.emplace_back("wgzvqkxuqrsqxs");
            input.emplace_back("dwneyqisozq");
            input.emplace_back("fg");
            input.emplace_back("vhfsf");
            input.emplace_back("uspujvqhydw");
            input.emplace_back("eadosqafyxbmzgr");
            input.emplace_back("tyff");
            input.emplace_back("blolplosqnfcwx");
            input.emplace_back("uwkl");
            input.emplace_back("puenodlvotb");
            input.emplace_back("iizudxqjvfnky");
            input.emplace_back("cjcywjkfvukvveq");
            input.emplace_back("jrxd");
            input.emplace_back("igwb");
            input.emplace_back("dftdyelydzyummmt");
            input.emplace_back("uvfmaicednym");
            input.emplace_back("oai");
            input.emplace_back("higfkfavgeemcgo");
            input.emplace_back("naefganqo");
            input.emplace_back("iqebfibigljbc");
            input.emplace_back("ulicojzjfrc");
            input.emplace_back("igxprunj");
            input.emplace_back("cymbrl");
            input.emplace_back("fqmwciqtynca");
            input.emplace_back("zjyagi");
            input.emplace_back("mzuejrttefhdwqc");
            input.emplace_back("zyiurxvf");
            input.emplace_back("wrjxffzbjexsh");
            input.emplace_back("wrxw");
            input.emplace_back("mhrbdxjwi");
            input.emplace_back("htknfa");
            input.emplace_back("wfrvxqdkhbwwef");
            input.emplace_back("vqsghhhutdget");
            input.emplace_back("cwupzrts");
            input.emplace_back("hbjnb");
            input.emplace_back("wpccoa");
            input.emplace_back("nx");
            input.emplace_back("howbzhaoscgyk");
            input.emplace_back("bilt");
            input.emplace_back("wqqatye");
            input.emplace_back("zceuuwg");
            input.emplace_back("jxzon");
            input.emplace_back("kkfj");
            input.emplace_back("bwsezd");
            input.emplace_back("ifdegsyjtswselk");
            input.emplace_back("xweimxlnzoh");
            input.emplace_back("tqthlftjblnpht");
            input.emplace_back("ww");
            input.emplace_back("ss");
            input.emplace_back("b");
            input.emplace_back("jmruuqscwjp");
            input.emplace_back("nxbk");
            input.emplace_back("wd");
            input.emplace_back("cqkrtbxgzg");
            input.emplace_back("xhppcjnq");
            input.emplace_back("cfq");
            input.emplace_back("tkkolzcfi");
            input.emplace_back("wblxki");
            input.emplace_back("ijeglxsvc");
            input.emplace_back("kcqjjwcwuhvzydm");
            input.emplace_back("gubqavlqffhrzz");
            input.emplace_back("hiwxrgftittd");
            input.emplace_back("caybc");
            input.emplace_back("ncsyjlzlxyyklc");
            input.emplace_back("poxcgnexmaajzuha");
            input.emplace_back("dhaccuualacyl");
            input.emplace_back("mtkewbprs");
            input.emplace_back("oncggqvr");
            input.emplace_back("sqqoffmwkplsgbrp");
            input.emplace_back("ioajuppvqluhbdet");
            input.emplace_back("dzwwzaelmo");
            input.emplace_back("afumtqugec");
            input.emplace_back("wglucmugwqi");
            input.emplace_back("zveswrjevfz");
            input.emplace_back("nxlbkak");
            input.emplace_back("pzcejvxzeoybb");
            input.emplace_back("fd");
            input.emplace_back("vewj");
            input.emplace_back("ivws");
            input.emplace_back("zjhudtpqsfc");
            input.emplace_back("zcmukotirrxx");
            input.emplace_back("zksmx");
            input.emplace_back("umofzhhowyftz");
            input.emplace_back("zbotrokaxaryxlk");
            input.emplace_back("ueolqk");
            input.emplace_back("dxmzhoq");
            input.emplace_back("zvu");
            input.emplace_back("cjl");
            input.emplace_back("esfmqgvxwfy");
            input.emplace_back("npbep");
            input.emplace_back("vbgjtbv");
            input.emplace_back("poeugoqynkbfiv");
            input.emplace_back("fewjjscjrei");
            input.emplace_back("yqssxzsydgllfzmo");
            input.emplace_back("urxkwcypctjkabi");
            input.emplace_back("wqtldwhjouas");
            input.emplace_back("tovdtkr");
            input.emplace_back("onzgeyddkqwuhnim");
            input.emplace_back("ffxviyvsktqrfa");
            input.emplace_back("qujhd");
            input.emplace_back("pvcz");
            input.emplace_back("hiyjlkxmeplnrvxg");
            input.emplace_back("hdykehkefp");
            input.emplace_back("vepcxhozpjxtreyn");
            input.emplace_back("liguhuxudbnh");
            input.emplace_back("f");
            input.emplace_back("ordxzm");
            input.emplace_back("klgohcmmbukz");
            input.emplace_back("yrmooliaobbnlap");
            input.emplace_back("dutnbetocxylcey");
            input.emplace_back("ywdsjegd");
            input.emplace_back("cr");
            input.emplace_back("blbxhjsgcuoxmqft");
            input.emplace_back("ngzdc");
            input.emplace_back("srfyjjumcbxole");
            input.emplace_back("dazwzwtdjoyuqeqj");
            input.emplace_back("xazjarqgfm");
            input.emplace_back("fxyfqbeoktcc");
            input.emplace_back("qrsjchxp");
            input.emplace_back("iltaqzawhgu");
            input.emplace_back("sgenjcfxr");
            input.emplace_back("yfikp");
            input.emplace_back("dvwhbyumthkiktb");
            input.emplace_back("walsx");
            input.emplace_back("jyajrkcvysicisab");
            input.emplace_back("brdeumb");
            input.emplace_back("tviihjwxdcz");
            input.emplace_back("dnrrgmem");
            input.emplace_back("ydgxlrjzucxyid");
            input.emplace_back("cdvdpvjlagwmg");
            input.emplace_back("ngnpxjkxims");
            input.emplace_back("gvyhnchlimsxc");
            input.emplace_back("w");
            input.emplace_back("jtizpezjl");
            input.emplace_back("qe");
            input.emplace_back("rjzv");
            input.emplace_back("vhnqvi");
            input.emplace_back("qm");
            input.emplace_back("iedzqswrsnfmnn");
            input.emplace_back("lt");
            input.emplace_back("utqfcqyrrwm");
            input.emplace_back("wtelvsqrru");
            input.emplace_back("fjwrhjcrtbcytn");
            input.emplace_back("qmqxceuohpiffaq");
            input.emplace_back("rmoybqjjgdyo");
            input.emplace_back("pmxttqftypfexlv");
            input.emplace_back("tg");
            input.emplace_back("qa");
            input.emplace_back("iqbqjlnpbf");
            input.emplace_back("kgaynkddbzllecd");
            input.emplace_back("tccvslp");
            input.emplace_back("curkxfoimnw");
            input.emplace_back("fvnyqkzlheruxr");
            input.emplace_back("iiygnzfov");
            input.emplace_back("coqs");
            input.emplace_back("oa");
            input.emplace_back("eiu");
            input.emplace_back("vzemmxtklis");
            input.emplace_back("lxu");
            input.emplace_back("nrwsjaxzwmh");
            input.emplace_back("tdayz");
            input.emplace_back("oxbbemejgosgcynf");
            input.emplace_back("ykbcn");
            input.emplace_back("hesvnctfvdsp");
            input.emplace_back("ku");
            input.emplace_back("rjhykpadahbhj");
            input.emplace_back("at");
            input.emplace_back("sxlngbtxmqr");
            input.emplace_back("wqrom");
            input.emplace_back("qzyabzrco");
            input.emplace_back("rbbyklndcqdj");
            input.emplace_back("cnsmgmwmpbgjq");
            input.emplace_back("krvnaf");
            input.emplace_back("qrwfajnfahyqocdb");
            input.emplace_back("fnlaozmff");
            input.emplace_back("vmoymbmytjvfcgt");
            input.emplace_back("cijyy");
            input.emplace_back("jdgwjbztl");
            input.emplace_back("swmalgbgpaplqgz");
            input.emplace_back("hfl");
            input.emplace_back("typttkrpfvx");
            input.emplace_back("tkzpzrscwbx");
            input.emplace_back("bwfqqvjcukjbsg");
            input.emplace_back("nxqmxr");
            input.emplace_back("x");
            input.emplace_back("eyavnz");
            input.emplace_back("il");
            input.emplace_back("dhthp");
            input.emplace_back("eyelg");
            input.emplace_back("npsoqsw");
            input.emplace_back("reogbmveofvusdsx");
            input.emplace_back("jvdrjkhxkq");
            input.emplace_back("qzjbrpljwuzpl");
            input.emplace_back("czqeevvbvcwh");
            input.emplace_back("vzuszqvhlmapty");
            input.emplace_back("yu");
            input.emplace_back("yldwwgezlqur");
            input.emplace_back("vorxwgdtgjilgydq");
            input.emplace_back("pknt");
            input.emplace_back("bgihl");
            input.emplace_back("ckorgrm");
            input.emplace_back("ixylxjmlfv");
            input.emplace_back("bpoaboylced");
            input.emplace_back("zea");
            input.emplace_back("igfagitkrext");
            input.emplace_back("ipvqq");
            input.emplace_back("dmoerc");
            input.emplace_back("oqxbypihdv");
            input.emplace_back("dtjrrkxro");
            input.emplace_back("rexuhucxpi");
            input.emplace_back("bvmuyarjwqpcoywa");
            input.emplace_back("qwdmfpwvamisns");
            input.emplace_back("bhopoqdsref");
            input.emplace_back("tmnm");
            input.emplace_back("cre");
            input.emplace_back("ktrniqwoofoeenbz");
            input.emplace_back("vlrfcsftapyujmw");
            input.emplace_back("updqikocrdyex");
            input.emplace_back("bcxw");
            input.emplace_back("eaum");
            input.emplace_back("oklsqebuzeziisw");
            input.emplace_back("fzgyhvnwjcns");
            input.emplace_back("dybjywyaodsyw");
            input.emplace_back("lmu");
            input.emplace_back("eocfru");
            input.emplace_back("ztlbggsuzctoc");
            input.emplace_back("ilfzpszgrgj");
            input.emplace_back("imqypqo");
            input.emplace_back("fump");
            input.emplace_back("sjvmsbrcfwretbie");
            input.emplace_back("oxpmplpcg");
            input.emplace_back("wmqigymr");
            input.emplace_back("qevdyd");
            input.emplace_back("gmuyytguexnyc");
            input.emplace_back("hwialkbjgzc");
            input.emplace_back("lmg");
            input.emplace_back("gijjy");
            input.emplace_back("lplrsxznfkoklxlv");
            input.emplace_back("xrbasbznvxas");
            input.emplace_back("twn");
            input.emplace_back("bhqultkyfq");
            input.emplace_back("saeq");
            input.emplace_back("xbuw");
            input.emplace_back("zd");
            input.emplace_back("kng");
            input.emplace_back("uoay");
            input.emplace_back("kfykd");
            input.emplace_back("armuwp");
            input.emplace_back("gtghfxf");
            input.emplace_back("gpucqwbihemixqmy");
            input.emplace_back("jedyedimaa");
            input.emplace_back("pbdrx");
            input.emplace_back("toxmxzimgfao");
            input.emplace_back("zlteob");
            input.emplace_back("adoshnx");
            input.emplace_back("ufgmypupei");
            input.emplace_back("rqyex");
            input.emplace_back("ljhqsaneicvaerqx");
            input.emplace_back("ng");
            input.emplace_back("sid");
            input.emplace_back("zagpiuiia");
            input.emplace_back("re");
            input.emplace_back("oadojxmvgqgdodw");
            input.emplace_back("jszyeruwnupqgmy");
            input.emplace_back("jxigaskpj");
            input.emplace_back("zpsbhgokwtfcisj");
            input.emplace_back("vep");
            input.emplace_back("ebwrcpafxzhb");
            input.emplace_back("gjykhz");
            input.emplace_back("mfomgxjphcscuxj");
            input.emplace_back("iwbdvusywqlsc");
            input.emplace_back("opvrnx");
            input.emplace_back("mkgiwfvqfkotpdz");
            input.emplace_back("inpobubzbvstk");
            input.emplace_back("vubuucilxyh");
            input.emplace_back("bci");
            input.emplace_back("dibmye");
            input.emplace_back("rlcnvnuuqfvhw");
            input.emplace_back("oorbyyiigppuft");
            input.emplace_back("swpksfdxicemjbf");
            input.emplace_back("goabwrqdoudf");
            input.emplace_back("yjutkeqakoarru");
            input.emplace_back("wuznnlyd");
            input.emplace_back("vfelxvtggkkk");
            input.emplace_back("mxlwbkbklbwfsvr");
            input.emplace_back("advraqovan");
            input.emplace_back("smkln");
            input.emplace_back("jxxvzdjlpyurxpj");
            input.emplace_back("ssebtpznwoytjefo");
            input.emplace_back("dynaiukctgrzjx");
            input.emplace_back("irzosjuncvh");
            input.emplace_back("hcnhhrajahitn");
            input.emplace_back("vwtifcoqepqyzwya");
            input.emplace_back("kddxywvgqxo");
            input.emplace_back("syxngevs");
            input.emplace_back("batvzmziq");
            input.emplace_back("mjewiyo");
            input.emplace_back("pzsupxoflq");
            input.emplace_back("byzhtvvpj");
            input.emplace_back("cqnlvlzr");
            input.emplace_back("akvmxzbaei");
            input.emplace_back("mwo");
            input.emplace_back("vg");
            input.emplace_back("ekfkuajjogbxhjii");
            input.emplace_back("isdbplotyak");
            input.emplace_back("jvkmxhtmyznha");
            input.emplace_back("lqjnqzrwrmgt");
            input.emplace_back("mbbhfli");
            input.emplace_back("bpeohsufree");
            input.emplace_back("ajrcsfogh");
            input.emplace_back("lucidbnlysamvy");
            input.emplace_back("tutjdfnvhahxy");
            input.emplace_back("urbrmmadea");
            input.emplace_back("hghv");
            input.emplace_back("acnjx");
            input.emplace_back("athltizloasimp");
            input.emplace_back("gu");
            input.emplace_back("rjfozvgmdakdhao");
            input.emplace_back("iephs");
            input.emplace_back("uztnpqhdl");
            input.emplace_back("rfuyp");
            input.emplace_back("crcszmgplszwfn");
            input.emplace_back("zihegt");
            input.emplace_back("xbspa");
            input.emplace_back("cjbmsamjyqqrasz");
            input.emplace_back("ghzlgnfoas");
            input.emplace_back("ljxl");
            input.emplace_back("cnumquohlcgt");
            input.emplace_back("jm");
            input.emplace_back("mfccj");
            input.emplace_back("hfedli");
            input.emplace_back("vtpieworwhyiucs");
            input.emplace_back("tdtuquartspkotm");
            input.emplace_back("pnkeluekvelj");
            input.emplace_back("ugrloq");
            input.emplace_back("zljmwt");
            input.emplace_back("fkyvqguqq");
            input.emplace_back("tpjidglpxqfxv");
            input.emplace_back("l");
            input.emplace_back("tvvimvroz");
            input.emplace_back("yy");
            input.emplace_back("opwyfovdz");
            input.emplace_back("pwlumocnyuoume");
            input.emplace_back("vjqpzkcfc");
            input.emplace_back("ihicd");
            input.emplace_back("dtttiixlhpikbv");
            input.emplace_back("goblttgvmndkqgg");
            input.emplace_back("gwsibcqahmyyeagk");
            input.emplace_back("prtvoju");
            input.emplace_back("lcblwidhjpu");
            input.emplace_back("kbu");
            input.emplace_back("pey");
            input.emplace_back("gkzrpc");
            input.emplace_back("bqajopjjlfthe");
            input.emplace_back("bc");
            input.emplace_back("lqs");
            input.emplace_back("zkndgojnjnxqsoqi");
            input.emplace_back("zyesldujjlp");
            input.emplace_back("drswybwlfyzph");
            input.emplace_back("xzluwbtmoxokk");
            input.emplace_back("bedrqfui");
            input.emplace_back("opajzeahv");
            input.emplace_back("lehdfnr");
            input.emplace_back("mnlpimduzgmwszc");
            input.emplace_back("velbhj");
            input.emplace_back("miwdn");
            input.emplace_back("wruqc");
            input.emplace_back("kscfodjxg");
            input.emplace_back("wcbm");
            auto ans = Solution::findAllConcatenatedWordsInADict(input);
            vector<string> output = vector<string>();
            output.emplace_back("gfve");
            output.emplace_back("qfpd");
            output.emplace_back("lqdqrrcrwdnxeuo");
            output.emplace_back("hbsfyfv");
            output.emplace_back("ife");
            output.emplace_back("feclhbvfuk");
            output.emplace_back("ngbqqmbxqcqp");
            output.emplace_back("khhqr");
            output.emplace_back("dwfcayssyoqc");
            output.emplace_back("omwufbdfxu");
            output.emplace_back("ilebxwbcto");
            output.emplace_back("ta");
            output.emplace_back("hbuxhwadlpto");
            output.emplace_back("tpvo");
            output.emplace_back("phckcyufdqml");
            output.emplace_back("lfz");
            output.emplace_back("tgygdt");
            output.emplace_back("nhcvpf");
            output.emplace_back("shwywshtdgmb");
            output.emplace_back("bkkxcvg");
            output.emplace_back("monmwvytby");
            output.emplace_back("qtg");
            output.emplace_back("cwkuzyamnerp");
            output.emplace_back("ye");
            output.emplace_back("tfsrptug");
            output.emplace_back("gama");
            output.emplace_back("nberblt");
            output.emplace_back("mf");
            output.emplace_back("gttxwpuk");
            output.emplace_back("xbrtspfttota");
            output.emplace_back("qxru");
            output.emplace_back("phknqtsdtwxcktmw");
            output.emplace_back("pbqurqfxgqlojmws");
            output.emplace_back("hdkbdxqg");
            output.emplace_back("ge");
            output.emplace_back("ukmcowoe");
            output.emplace_back("xdnnl");
            output.emplace_back("yjyssbsoc");
            output.emplace_back("uvouaghhcyvmlk");
            output.emplace_back("pbcnmhf");
            output.emplace_back("qmmidmvkn");
            output.emplace_back("xmywegmtuno");
            output.emplace_back("vuzygv");
            output.emplace_back("uxtrdsdfzfssmel");
            output.emplace_back("eqrswgkaaaohxx");
            output.emplace_back("ocedkt");
            output.emplace_back("qghoy");
            output.emplace_back("wsx");
            output.emplace_back("glafbwzdd");
            output.emplace_back("ryp");
            output.emplace_back("nvybsfrxtlfmp");
            output.emplace_back("upmsoxftumyxifyu");
            output.emplace_back("xucubv");
            output.emplace_back("fctkqlroq");
            output.emplace_back("ppvs");
            output.emplace_back("nwedtubynsb");
            output.emplace_back("repgcx");
            output.emplace_back("gsfomhvpmy");
            output.emplace_back("kdohe");
            output.emplace_back("llkmagl");
            output.emplace_back("thkglauzgkeuly");
            output.emplace_back("paeurdvexqlw");
            output.emplace_back("akdt");
            output.emplace_back("rqdll");
            output.emplace_back("mumbh");
            output.emplace_back("br");
            output.emplace_back("fso");
            output.emplace_back("qnebmfl");
            output.emplace_back("lq");
            output.emplace_back("xbhkkfg");
            output.emplace_back("ax");
            output.emplace_back("gqgsomonv");
            output.emplace_back("reqqzzpw");
            output.emplace_back("rlbskqgfvn");
            output.emplace_back("lfvobeyolyy");
            output.emplace_back("mwrvel");
            output.emplace_back("ogwilaswn");
            output.emplace_back("yw");
            output.emplace_back("egdgye");
            output.emplace_back("yaqgault");
            output.emplace_back("dtlg");
            output.emplace_back("iddymnl");
            output.emplace_back("evxtehxtbthq");
            output.emplace_back("brxpfymuvfvs");
            output.emplace_back("rv");
            output.emplace_back("udvmara");
            output.emplace_back("fecd");
            output.emplace_back("dfuydrtbfypbn");
            output.emplace_back("cypqodxr");
            output.emplace_back("vkmxys");
            output.emplace_back("wvpfyfpkvgthq");
            output.emplace_back("av");
            output.emplace_back("vwduwmjpblqo");
            output.emplace_back("xwnbcuggl");
            output.emplace_back("flhyfac");
            output.emplace_back("mqrbq");
            output.emplace_back("pstsxhplrrmbeddv");
            output.emplace_back("hnegtuxx");
            output.emplace_back("bhhlovgcx");
            output.emplace_back("had");
            output.emplace_back("aysulvk");
            output.emplace_back("potn");
            output.emplace_back("os");
            output.emplace_back("np");
            output.emplace_back("lhv");
            output.emplace_back("uzvgyeette");
            output.emplace_back("tp");
            output.emplace_back("wtsbhgkd");
            output.emplace_back("eouxbldsxzm");
            output.emplace_back("xhnlcrldtfthul");
            output.emplace_back("xhflc");
            output.emplace_back("rlaks");
            output.emplace_back("phouoyhvls");
            output.emplace_back("dqhqats");
            output.emplace_back("koat");
            output.emplace_back("pybf");
            output.emplace_back("po");
            output.emplace_back("wygsnxk");
            output.emplace_back("kqlima");
            output.emplace_back("fgxnuohrnhg");
            output.emplace_back("wnnbq");
            output.emplace_back("mdtrgv");
            output.emplace_back("nkq");
            output.emplace_back("agylw");
            output.emplace_back("vomtuy");
            output.emplace_back("vtdxwrclpspcn");
            output.emplace_back("rdrls");
            output.emplace_back("yxfeoh");
            output.emplace_back("myctacn");
            output.emplace_back("fdnor");
            output.emplace_back("qfzwuwe");
            output.emplace_back("svo");
            output.emplace_back("dc");
            output.emplace_back("odknlbvxrs");
            output.emplace_back("hwc");
            output.emplace_back("erpbaxq");
            output.emplace_back("rrklkb");
            output.emplace_back("wlrwyuy");
            output.emplace_back("yyhga");
            output.emplace_back("xwdbycdu");
            output.emplace_back("htedgvsrhchox");
            output.emplace_back("wr");
            output.emplace_back("suhesetv");
            output.emplace_back("qcagsyqggcf");
            output.emplace_back("wljmg");
            output.emplace_back("npdbamofynykqv");
            output.emplace_back("lmq");
            output.emplace_back("oyjmeqvhcrvgm");
            output.emplace_back("nxtsnason");
            output.emplace_back("gbndakaq");
            output.emplace_back("hrtbfnq");
            output.emplace_back("fguvomeepxoffg");
            output.emplace_back("mat");
            output.emplace_back("onlvy");
            output.emplace_back("cwcchvsasdylb");
            output.emplace_back("dphbfaal");
            output.emplace_back("mabkapuoud");
            output.emplace_back("vl");
            output.emplace_back("ffjfb");
            output.emplace_back("svthrfmkoxbho");
            output.emplace_back("cvet");
            output.emplace_back("ucgqyvopafyttrh");
            output.emplace_back("vruh");
            output.emplace_back("ukffmudygjavem");
            output.emplace_back("dccamymhp");
            output.emplace_back("kmm");
            output.emplace_back("sc");
            output.emplace_back("soqlh");
            output.emplace_back("gcdqbcdwbwa");
            output.emplace_back("gadgt");
            output.emplace_back("pgowefka");
            output.emplace_back("cpdxf");
            output.emplace_back("sox");
            output.emplace_back("fq");
            output.emplace_back("lfnrhgsxkhx");
            output.emplace_back("loc");
            output.emplace_back("fkglorkkvx");
            output.emplace_back("ggk");
            output.emplace_back("nraoenhd");
            output.emplace_back("rrbhfwohfv");
            output.emplace_back("yoifoyg");
            output.emplace_back("ahmv");
            output.emplace_back("byyvhgh");
            output.emplace_back("hyw");
            output.emplace_back("kedhvwy");
            output.emplace_back("rglnpxfqwu");
            output.emplace_back("su");
            output.emplace_back("mbntqrlwyampdg");
            output.emplace_back("jfymrbafmyoc");
            output.emplace_back("rhymsno");
            output.emplace_back("rkbdlchs");
            output.emplace_back("ocbbwwd");
            output.emplace_back("exlwulswtvot");
            output.emplace_back("tlnc");
            output.emplace_back("eo");
            output.emplace_back("ua");
            output.emplace_back("khxkdxflwxme");
            output.emplace_back("kk");
            output.emplace_back("cw");
            output.emplace_back("pxnktxkm");
            output.emplace_back("aa");
            output.emplace_back("ngrwqpoh");
            output.emplace_back("rwuvd");
            output.emplace_back("eruffmlg");
            output.emplace_back("bxzovyew");
            output.emplace_back("hyfrdngjf");
            output.emplace_back("ly");
            output.emplace_back("pfgsp");
            output.emplace_back("akyprzzphew");
            output.emplace_back("ubheeqt");
            output.emplace_back("rmbxlcmn");
            output.emplace_back("apsbu");
            output.emplace_back("khwnykughmwrlk");
            output.emplace_back("mvndmua");
            output.emplace_back("nlwpw");
            output.emplace_back("btgcpqwovwp");
            output.emplace_back("sfzdknoxzassc");
            output.emplace_back("fg");
            output.emplace_back("vhfsf");
            output.emplace_back("tyff");
            output.emplace_back("blolplosqnfcwx");
            output.emplace_back("uwkl");
            output.emplace_back("puenodlvotb");
            output.emplace_back("naefganqo");
            output.emplace_back("cymbrl");
            output.emplace_back("wrxw");
            output.emplace_back("htknfa");
            output.emplace_back("wfrvxqdkhbwwef");
            output.emplace_back("vqsghhhutdget");
            output.emplace_back("wpccoa");
            output.emplace_back("nx");
            output.emplace_back("bilt");
            output.emplace_back("wqqatye");
            output.emplace_back("bwsezd");
            output.emplace_back("ww");
            output.emplace_back("ss");
            output.emplace_back("jmruuqscwjp");
            output.emplace_back("nxbk");
            output.emplace_back("wd");
            output.emplace_back("cfq");
            output.emplace_back("gubqavlqffhrzz");
            output.emplace_back("caybc");
            output.emplace_back("dhaccuualacyl");
            output.emplace_back("mtkewbprs");
            output.emplace_back("oncggqvr");
            output.emplace_back("sqqoffmwkplsgbrp");
            output.emplace_back("afumtqugec");
            output.emplace_back("nxlbkak");
            output.emplace_back("fd");
            output.emplace_back("ueolqk");
            output.emplace_back("esfmqgvxwfy");
            output.emplace_back("npbep");
            output.emplace_back("yqssxzsydgllfzmo");
            output.emplace_back("tovdtkr");
            output.emplace_back("hdykehkefp");
            output.emplace_back("ordxzm");
            output.emplace_back("dutnbetocxylcey");
            output.emplace_back("cr");
            output.emplace_back("ngzdc");
            output.emplace_back("fxyfqbeoktcc");
            output.emplace_back("walsx");
            output.emplace_back("brdeumb");
            output.emplace_back("dnrrgmem");
            output.emplace_back("gvyhnchlimsxc");
            output.emplace_back("qe");
            output.emplace_back("qm");
            output.emplace_back("lt");
            output.emplace_back("utqfcqyrrwm");
            output.emplace_back("wtelvsqrru");
            output.emplace_back("qmqxceuohpiffaq");
            output.emplace_back("pmxttqftypfexlv");
            output.emplace_back("tg");
            output.emplace_back("qa");
            output.emplace_back("tccvslp");
            output.emplace_back("coqs");
            output.emplace_back("oa");
            output.emplace_back("lxu");
            output.emplace_back("ykbcn");
            output.emplace_back("hesvnctfvdsp");
            output.emplace_back("ku");
            output.emplace_back("at");
            output.emplace_back("sxlngbtxmqr");
            output.emplace_back("wqrom");
            output.emplace_back("krvnaf");
            output.emplace_back("hfl");
            output.emplace_back("typttkrpfvx");
            output.emplace_back("nxqmxr");
            output.emplace_back("dhthp");
            output.emplace_back("eyelg");
            output.emplace_back("npsoqsw");
            output.emplace_back("reogbmveofvusdsx");
            output.emplace_back("yu");
            output.emplace_back("pknt");
            output.emplace_back("ckorgrm");
            output.emplace_back("bpoaboylced");
            output.emplace_back("dmoerc");
            output.emplace_back("bhopoqdsref");
            output.emplace_back("tmnm");
            output.emplace_back("cre");
            output.emplace_back("vlrfcsftapyujmw");
            output.emplace_back("bcxw");
            output.emplace_back("eaum");
            output.emplace_back("dybjywyaodsyw");
            output.emplace_back("lmu");
            output.emplace_back("eocfru");
            output.emplace_back("fump");
            output.emplace_back("oxpmplpcg");
            output.emplace_back("qevdyd");
            output.emplace_back("gmuyytguexnyc");
            output.emplace_back("lmg");
            output.emplace_back("lplrsxznfkoklxlv");
            output.emplace_back("twn");
            output.emplace_back("bhqultkyfq");
            output.emplace_back("saeq");
            output.emplace_back("xbuw");
            output.emplace_back("kng");
            output.emplace_back("uoay");
            output.emplace_back("kfykd");
            output.emplace_back("armuwp");
            output.emplace_back("gtghfxf");
            output.emplace_back("pbdrx");
            output.emplace_back("adoshnx");
            output.emplace_back("rqyex");
            output.emplace_back("ng");
            output.emplace_back("sid");
            output.emplace_back("re");
            output.emplace_back("vep");
            output.emplace_back("ebwrcpafxzhb");
            output.emplace_back("opvrnx");
            output.emplace_back("vubuucilxyh");
            output.emplace_back("rlcnvnuuqfvhw");
            output.emplace_back("goabwrqdoudf");
            output.emplace_back("wuznnlyd");
            output.emplace_back("vfelxvtggkkk");
            output.emplace_back("mxlwbkbklbwfsvr");
            output.emplace_back("advraqovan");
            output.emplace_back("smkln");
            output.emplace_back("kddxywvgqxo");
            output.emplace_back("syxngevs");
            output.emplace_back("mwo");
            output.emplace_back("vg");
            output.emplace_back("bpeohsufree");
            output.emplace_back("lucidbnlysamvy");
            output.emplace_back("urbrmmadea");
            output.emplace_back("hghv");
            output.emplace_back("gu");
            output.emplace_back("uztnpqhdl");
            output.emplace_back("rfuyp");
            output.emplace_back("xbspa");
            output.emplace_back("cnumquohlcgt");
            output.emplace_back("tdtuquartspkotm");
            output.emplace_back("ugrloq");
            output.emplace_back("fkyvqguqq");
            output.emplace_back("yy");
            output.emplace_back("pwlumocnyuoume");
            output.emplace_back("goblttgvmndkqgg");
            output.emplace_back("lcblwidhjpu");
            output.emplace_back("kbu");
            output.emplace_back("pey");
            output.emplace_back("bc");
            output.emplace_back("lqs");
            output.emplace_back("xzluwbtmoxokk");
            output.emplace_back("lehdfnr");
            output.emplace_back("wruqc");
            output.emplace_back("wcbm");
            for (const string &str: ans) {
                ASSERT_TRUE(find(output.cbegin(), output.cend(), str) != output.cend());
            }
            for (const string &str: output) {
                ASSERT_TRUE(find(ans.cbegin(), ans.cend(), str) != ans.cend());
            }
            ASSERT_EQ(ans.size(), output.size());
        }

        TEST(concatenated_words, case4) {
            vector<basic_string<char>> input = vector<basic_string<char>>();
            input.emplace_back("nuqhmfj");
            input.emplace_back("mf");
            input.emplace_back("jf");
            input.emplace_back("n");
            input.emplace_back("u");
            input.emplace_back("q");
            input.emplace_back("h");
            auto ans = Solution::findAllConcatenatedWordsInADict(input);
            vector<string> output = vector<string>();
            for (const string &str: ans) {
                ASSERT_TRUE(find(output.cbegin(), output.cend(), str) != output.cend());
            }
            for (const string &str: output) {
                ASSERT_TRUE(find(ans.cbegin(), ans.cend(), str) != ans.cend());
            }
            ASSERT_EQ(ans.size(), output.size());
        }
    }

    namespace count_special_quadruplets {
        TEST(count_special_quadruplets, case1) {
            vector<int> vec = vector<int>();
            vec.push_back(1);
            vec.push_back(2);
            vec.push_back(3);
            vec.push_back(6);
            ASSERT_EQ(1, Solution::countQuadruplets(vec));
        }

        TEST(count_special_quadruplets, case2) {
            vector<int> vec = vector<int>();
            vec.push_back(3);
            vec.push_back(3);
            vec.push_back(6);
            vec.push_back(4);
            vec.push_back(5);
            ASSERT_EQ(0, Solution::countQuadruplets(vec));
        }

        TEST(count_special_quadruplets, case3) {
            vector<int> vec = vector<int>();
            vec.push_back(1);
            vec.push_back(1);
            vec.push_back(1);
            vec.push_back(3);
            vec.push_back(5);
            ASSERT_EQ(4, Solution::countQuadruplets(vec));
        }

        TEST(count_special_quadruplets, case4) {
            vector<int> vec = vector<int>();
            vec.push_back(28);
            vec.push_back(8);
            vec.push_back(49);
            vec.push_back(85);
            vec.push_back(37);
            vec.push_back(90);
            vec.push_back(20);
            vec.push_back(8);
            ASSERT_EQ(1, Solution::countQuadruplets(vec));
        }
    }
}

namespace acwing {
    TEST(acwing1, case1) {
        istringstream in("3 4");
        ostringstream out;
        acwing1::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("7", ans);
    }

    TEST(acwing4200, case1) {
        istringstream in("2 7 1 8 2 8");
        ostringstream out;
        acwing4200::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("0", ans);
    }

    TEST(acwing4200, case2) {
        istringstream in("20 30 40 50 0 100");
        ostringstream out;
        acwing4200::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("20", ans);
    }

    TEST(acwing4200, case3) {
        istringstream in("31 41 59 26 17 43");
        ostringstream out;
        acwing4200::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("9", ans);
    }

    TEST(acwing4201, case1) {
        istringstream in("10");
        ostringstream out;
        acwing4201::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("2", ans);
    }

    TEST(acwing4201, case2) {
        istringstream in("20");
        ostringstream out;
        acwing4201::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("3", ans);
    }

    TEST(acwing4201, case3) {
        istringstream in("100");
        ostringstream out;
        acwing4201::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("4", ans);
    }

    TEST(acwing4201, case4) {
        istringstream in("1000");
        ostringstream out;
        acwing4201::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("8", ans);
    }

    TEST(acwing4201, case5) {
        istringstream in("10000");
        ostringstream out;
        acwing4201::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("16", ans);
    }

    TEST(acwing4201, case6) {
        istringstream in("200");
        ostringstream out;
        acwing4201::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("7", ans);
    }

    TEST(acwing4201, case7) {
        istringstream in("101");
        ostringstream out;
        acwing4201::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("5", ans);
    }

    TEST(acwing4201, case8) {
        istringstream in("1");
        ostringstream out;
        acwing4201::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("1", ans);
    }

    TEST(acwing4201, case9) {
        istringstream in("102");
        ostringstream out;
        acwing4201::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("5", ans);
    }

    TEST(acwing4201, case10) {
        istringstream in("111");
        ostringstream out;
        acwing4201::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("7", ans);
    }

    TEST(acwing4201, case11) {
        istringstream in("110");
        ostringstream out;
        acwing4201::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("6", ans);
    }

    TEST(acwing610, case1) {
        istringstream in("5\n6\n7\n8");
        ostringstream out;
        acwing610::main(in, out);
        auto ans = out.str();
        ASSERT_EQ("DIFERENCA = -26", ans);
    }
}

namespace lintcode {
    namespace lintcode1214 {
        TEST(lintcode1214, case1) {
            string s = string("5F3Z-2e-9-w");
            ASSERT_EQ("5F3Z-2E9W", Solution::licenseKeyFormatting(s, 4));
        }

        TEST(lintcode1214, case2) {
            string s = string("2-5g-3-J");
            ASSERT_EQ("2-5G-3J", Solution::licenseKeyFormatting(s, 2));
        }
    }
}
