# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}/build'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  gendoc_and_publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Gendoc
        uses: langroodi/doxygenize@master
        with:
          doxygenconf: './Doxyfile'
          htmloutput: './'
          ghpagesbranch: 'gh-pages'
          ghpagesdir: './'

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Learn more about CodeQL language support at https://git.io/codeql-language-support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        # 更新: 使用 v3 版本
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      # 新增: 添加手动的构建步骤来替代 autobuild
      - name: Build C++ code
        run: |
          mkdir -p ${{ env.build }}
          cd ${{ env.build }}
          cmake ..
          make

      # 移除: 不再使用 autobuild
      # - name: Autobuild
      #   uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        # 更新: 使用 v3 版本
        uses: github/codeql-action/analyze@v3
